var Families = [
    {name: 'Agasha', attr: 'PER'},
    {name: 'Akodo', attr: 'AGI'},
    {name: 'Asahina', attr: 'INT'},
    {name: 'Asako', attr: 'AWA'},
    {name: 'Bayushi', attr: 'AGI'},
    {name: 'Chuda (Maj)', attr: 'INT'},
    {name: 'Chuda (Min)', attr: 'STR'},
    {name: 'Daidoji', attr: 'STA'},
    {name: 'Daigotsu', attr: 'STA'},
    {name: 'Doji', attr: 'AWA'},
    {name: 'Fuzake', attr: 'PER'},
    {name: 'Goju', attr: 'AGI'},
    {name: 'Hantei', attr: 'VOI'},
    {name: 'Heichi', attr: 'AWA'},
    {name: 'Hida', attr: 'STR'},
    {name: 'Hiruma', attr: 'AGI'},
    {name: 'Hitomi', attr: 'STR'},
    {name: 'Horiuchi', attr: 'WIL'},
    {name: 'Hoshi', attr: 'VOI'},
    {name: 'Ichiro', attr: 'STR'},
    {name: 'Ide', attr: 'PER'},
    {name: 'Ikoma', attr: 'AWA'},
    {name: 'Isawa', attr: 'WIL'},
    {name: 'Iuchi', attr: 'INT'},
    {name: 'Kaeru', attr: 'AWA'},
    {name: 'Kaiu', attr: 'INT'},
    {name: 'Kakita', attr: 'AGI'},
    {name: 'Kasuga', attr: 'PER'},
    {name: 'Kitsu', attr: 'INT'},
    {name: 'Kitsuki', attr: 'AWA'},
    {name: 'Kitsune (Majeur)', attr: 'AWA'},
    {name: 'Kitsune (Mineur)', attr: 'WIL'},
    {name: 'Komori', attr: 'INT'},
    {name: 'Kuni', attr: 'INT'},
    {name: 'Matsu', attr: 'STR'},
    {name: 'Mirumoto', attr: 'AGI'},
    {name: 'Miya', attr: 'REF'},
    {name: 'Moines Araignée', attr: 'REF'},
    {name: 'Morito', attr: 'STA'},
    {name: 'Moshi', attr: 'INT'},
    {name: 'Moto', attr: 'AGI'},
    {name: 'Otaku/Utaku', attr: 'STA'},
    {name: 'Otomo', attr: 'INT'},
    {name: 'Seppun', attr: 'AGI'},
    {name: 'Shiba', attr: 'PER'},
    {name: 'Shinjo', attr: 'REF'},
    {name: 'Shosuro', attr: 'AWA'},
    {name: 'Soshi', attr: 'INT'},
    {name: 'Susumu', attr: 'AWA'}
    {name: 'Suzume', attr: 'AWA'},
    {name: 'Togashi', attr: 'REF'},
    {name: 'Toku', attr: 'STA'},
    {name: 'Tonbo', attr: 'AWA'},
    {name: 'Toritaka', attr: 'PER'},
    {name: 'Toturi', attr: 'WIL'},
    {name: 'Tsi (Min)', attr: 'STR'},
    {name: 'Tsi (Ronin)', attr: 'WIL'},
    {name: 'Tsume', attr: 'REF'},
    {name: 'Tsuruchi', attr: 'PER'},
    {name: 'Ujina', attr: 'AGI'},
    {name: 'Usagi', attr: 'AWA'},
    {name: 'Yasuki', attr: 'AWA'},
    {name: 'Yogo', attr: 'WIL'},
    {name: 'Yoritomo', attr: 'STA'},
    {name: 'Yoshun', attr: 'AGI'},
    {name: 'Yotsu', attr: 'INT'},
];

var Schools = [];

var Skills = [];
